# .pre-commit-config.yaml
repos:
  # Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [css, markdown, text, svg]
      - id: trailing-whitespace
        exclude_types: [html, markdown, text]
      - id: check-merge-conflict
      - id: detect-private-key

  # Python spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        entry: codespell
        files: ^backend/
        types: [python]

  # Python linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        files: ^backend/
        exclude: __init__.py|migrations

  # JavaScript/TypeScript formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, json, css, scss, html, markdown]
        exclude: ^frontend/(build|dist|node_modules)/

  # JavaScript/TypeScript linting with ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.47.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@8.47.0
          - "@typescript-eslint/eslint-plugin@6.4.0"
          - "@typescript-eslint/parser@6.4.0"
          - eslint-plugin-react@7.33.1
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-import@2.28.0
        args: ["--fix", "--ignore-path", "^frontend/.eslintignore"]