"""add_refresh_token_expiration_to_users

Revision ID: 704bfb2f999b
Revises: 42815d8690ab
Create Date: 2025-09-20 15:16:31.890544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704bfb2f999b'
down_revision: Union[str, Sequence[str], None] = '42815d8690ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expires_at')
    # ### end Alembic commands ###
