"""Update audit entry

Revision ID: 88894c3ed182
Revises: d4d4cd27dbcc
Create Date: 2025-08-30 22:20:21.185425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88894c3ed182"
down_revision: Union[str, Sequence[str], None] = "d4d4cd27dbcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_entry",
        "created_by",
        existing_type=sa.VARCHAR(length=100, collation="Chinese_PRC_CI_AS"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_entry",
        "created_by",
        existing_type=sa.VARCHAR(length=100, collation="Chinese_PRC_CI_AS"),
        nullable=False,
    )
    # ### end Alembic commands ###
